services:
  db:
    container_name: db
    image: postgres:18
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - supr-network
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: ./apps/redis/Dockerfile
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks:
      - supr-network

  arena:
    container_name: arena
    build:
      context: .
      dockerfile: ./apps/arena/Dockerfile
    depends_on:
      - redis
    restart: always
    ports:
      - 4567:4567
    networks:
      - supr-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - 4000:4000
    networks:
      - supr-network
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}

networks:
  supr-network:

volumes:
  db-data:
